### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by faroit** [danburzo/percollate#112]
### Feature description

existing math code should be rendered correctly.
Example page: 

https://thegradient.pub/transformers-are-graph-neural-networks/

However, math is shown as code:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/72940/96571425-d704a900-12cb-11eb-8a11-3e7255882d48.png">

**Comment by danburzo** [comment]
Thanks for the report. Percollate is designed to work with the raw HTML markup, and it occasionally breaks for websites whose content relies on JavaScript. 

Since we can't execute the webpage's referenced scripts, what we can do is try to [run MathJax in Node.js](https://github.com/mathjax/MathJax-node) — or even better, [KaTeX](https://katex.org/)? — on the webpage's content. This would mean, however, that we take a guess on the markup used on the page (delimiter, syntax, etc.)

**Comment by danburzo** [comment]
Since LaTeX-on-the-web generally does not contain hints in the HTML markup about how to render it (with most libraries opting for a JS configuration API instead), we can't decide on the correct config to render math in web pages. Therefore unfortunately it sounds like we won't be able to add support in `percollate`.
