### ISSUE TITLE
support Pop-up Footnotes in EPUB  books ?

### ISSUE THREAD

**Issue by jinshuqishi2019** [danburzo/percollate#170]
## Feature description
Hello, now I have an html file with a commented document structure. I would like to ask if `percollate epub` supports it? If it does, what structure does the html need to be successfully converted? If not, then thank you anyway for providing such a convenient tool.

**Comment by danburzo** [comment]
Hi @jinshuqishi2019, while the EPUB specification supports specific markup patterns for producing pop-up footnotes, I don’t think it’s possible at the moment to craft a HTML page that produces the correct EPUB output, since the HTML is simplified with Readability.js. Maybe with a `--no-readability` option you would be able to implement something like that, but it needs some testing.

**Comment by jinshuqishi2019** [comment]
Thank you very much!
