### ISSUE TITLE
Allow proxy parameters

### ISSUE THREAD

**Issue by glmxndr** [danburzo/percollate#23]
`got` accepts proxy parameters. 

Either allow command line parameters for proxy to be passed over to got, or even better, honor `http_proxy`, `https_proxy`, `no_proxy` env variables.

**Comment by danburzo** [comment]
Thanks for the suggestion, sounds reasonable! I'll have to take a closer look...

**Comment by danburzo** [comment]
Starting with `v0.5.0`, percollate supports fetching the HTML externally, and using `-` as an operand to read from `stdin`. The `-u` / `--url` option allows you to pass the original URL, so that relative links and images resolve correctly.

Instead of: 

```bash
percollate pdf http://example.com
```

You can use `curl` for example:

```bash
curl http://example.com | percollate pdf --url http://example.com -
```

Going forward, I think it will be a good idea that any custom fetching happens outside percollate.
