### ISSUE TITLE
Default save location?

### ISSUE THREAD

**Issue by x-ji** [danburzo/percollate#37]
Sometimes I might just want to create PDFs from a list of web pages, using the page title as the default file name (using the page title is the default printing behavior of Chrome I believe).

Currently, if I run `percollate` without specifying `--output`, it claims to have saved the pdf, but I can't find it in the folder where I executed the command.

Can it just save the web page to the current folder using its title as the filename, when an `--output` flag is omitted?

**Comment by danburzo** [comment]
Thanks for the idea. I was not sure whether we should go for a default name when no output path is provided, or emit the PDF to `stdout`, so that the output can be piped to other commands. But since we already log things with `console.log` that would be picked up as well, so I guess having a default output path would work better.

Do you want to give it a shot in a PR? I'm thinking we can take the `title` property from the Readability output and run it through [slugify](https://www.npmjs.com/package/slugify). 

Also, what should we do for multiple webpages → PDF?

**Comment by x-ji** [comment]
Sure I might have time to work on it in a few days if nobody picks this up. This tool can be immensely helpful for me since I use the Sony DPT-RP1 to read long articles as PDFs.

For my use case I'd just want to save those different pages to different PDFs, as they are different articles. Previously I needed to manually print them one by one but with percollate hopefully one can produce the PDFs in one command. Maybe there's some other use case such as this one https://github.com/danburzo/percollate/issues/25, which I think is separate from my intended use case though.

**Comment by danburzo** [comment]
Sounds good. I guess for multiple files we can go with `percollate-<timestamp>.pdf` until we figure out a better name for a bundle. 

I think in #25 we're looking at using the programmatic API (#4) rather than trying to stretch the CLI to do it?

**Comment by danburzo** [comment]
Fixed in `percollate@0.2.9`, let me know how that works for you!

**Comment by x-ji** [comment]
It works. Thanks!

I think I misunderstood what you meant by multiple webpages. The current output is also useful, though ideally for me I'd want one separate PDF for one webpage, instead of putting all the pages into one PDF. Would that be hard to achieve? I might try to add this functionality, e.g. enabled by a flag.
