### ISSUE TITLE
Create pdf of pages behind authentication wall?

### ISSUE THREAD

**Issue by ganapativs** [danburzo/percollate#61]
Is there a way to configure cookie/local storage before visiting url to create pdf?

**Comment by danburzo** [comment]
[The underlying library](https://github.com/sindresorhus/got) we use for fetching the URL might have some options for this. If we can make it work with `got` (👉 [playground here](https://npm.runkit.com/got)), we can make it work with `percollate`.

P.S.: I've tagged [a few issues](https://github.com/danburzo/percollate/labels/Phase%3A%20Fetch) relevant to the fetch phase.

**Comment by ganapativs** [comment]
There is a [`header.cookieJar`](https://github.com/sindresorhus/got#cookiejar) in got. If we allow configuring headers while fetching the page, most of the things should be achievable.

**Comment by danburzo** [comment]
The current thinking around this is to fetch the contents externally whenever the request needs to be configured. For example:

```bash
curl https://example.com/page1 | percollate pdf --url=https://example.com/page1 -
```

Notice the `-` operand — this instructs percollate to read from stdin (which is the output of the previous `curl` command). We use the `--url` option to send back the original URL to percollate, so that relative links and images get resolved correctly.

I've also switched from `got` to the more lightweight `node-fetch` package.
