### ISSUE TITLE
Special case HN Comments to PDF

### ISSUE THREAD

**Issue by proful** [danburzo/percollate#65]
I tried to generate pdf from HN comments. 
ref: https://news.ycombinator.com/item?id=18267468
Looks like only question is converted to pdf. Not the comment thread. Not sure it is bug or the desired behavior.  But for HN reader, it's really wealth of information and definitely love to see it converted to pdf.

Your thoughts?

**Comment by tanmayrajani** [comment]
> use a completely different Reader View algorithm

I wonder how [Pocket](https://getpocket.com) does it.

**Comment by danburzo** [comment]
Another idea is to hack into Readability's regular expressions:

https://github.com/mozilla/readability/blob/3be1aaa01c078c25b67ed8dfd1c9aa8f9963490b/Readability.js#L113-L127

So that we can provide custom CSS classes / IDs for things we want to include (`positive`) or exclude (`negative`). I ran a quick test on a HN thread and including `comment` in the `positive` regexp worked to include it, but the rendering is all messed up due to the `<table>` in `<table>` layout HN uses. But it seems like a promising approach.

**Comment by butu5** [comment]
May be we can somehow extend this capability to command line argument like --css. So we can pass --positiveClass or --positiveId or something like that. Because each article may be slightly different needs.

**Comment by danburzo** [comment]
I've did just that in [this PR](https://github.com/danburzo/percollate/pull/75) where you can pass `--positive` and `--negative` CSS selectors, but apparently it's not enough to nudge Readability in the right direction for hacker news threads, or other articles for that matter.

On the same PR I am experimenting with a homegrown variety of Reader View functionality that is showing promising results.

**Comment by danburzo** [comment]
Closing this for now. It seems unlikely that we will be able to process correctly markup like the one featured on Hacker News threads with Readability / percollate.
