### ISSUE TITLE
Is it possible to override the source URL?

### ISSUE THREAD

**Issue by yang-ling** [danburzo/percollate#90]
Thanks for this awesome tool!

Here is the case, Percollate doesn't provide good enough PDF for some webpage, so I save the webpage, and do some modification, and then setup a simple local web server by `python3 -m http.server`. Then use Percollate to generate PDF by `percollate pdf --output my.pdf http://localhost:8000/my.html`

It works great, except the source URL. In generated PDF, source URL is included, and it is `Source -> http://localhost:8000/my.html`

What I want is to override that URL by the REAL URL, not the localhost one.

I have read the README but couldn't find a clue. Is it possible to do that?

If it is not supported yet, I'd like to contribute. My thought is to add an argument for this purpose, like `--url`, or `realurl`. How do you think?

**Comment by danburzo** [comment]
If the only problem is the _Source_ is inaccurate, but the page is otherwise generated correctly, I'd say that at this point it would make sense to use the existing API for achieving this. In particular, two helpful options.

With the `--css` option, you can hide the source that Percollate generates:

```
--css ".article__url { display: none; }"
```

See [the default HTML template](https://github.com/danburzo/percollate/blob/master/templates/default.html#L27-L46) for other classes you can use. 

Now, to introduce the (correct) source back into the PDF, you can either:

* include it as part of your page's content
* use the `--template` option to provide your own HTML template, and put the source there.

In the future, while we flesh out the programmatic API for Percollate, it would be much easier to obtain custom things. In the meantime, adding too many options to the command-line interface may not be the best approach.

Hope this helps!

**Comment by yang-ling** [comment]
@danburzo Thanks for your reply. 

> include it as part of your page's content

I am using this approach now.

> In the future, while we flesh out the programmatic API for Percollate, it would be much easier to obtain custom things. 

I'm looking forward to it

> In the meantime, adding too many options to the command-line interface may not be the best approach.

I agree.

Thanks again.
